### PR TITLE
ExApp version check

### PR DESCRIPTION
**Pull request by andrey18106**
- [x] Resolve conflicts
- [ ] Merge into auth throttling PR first

### CODE REVIEW

**Comment by bigcat88** [comment]
Thoughts:
1. Admin do not stops `ExApp` and updates it manually(with new Docker image).
2. New version of `ExApp` wants to register new stuff, it did not do that in this case.
3. App already got displayed as updated in NC, it can not be updated automaticly, as we just `imitate update here`.

**Comment by bigcat88** [comment]
First solution:

1. Got another version then expected
2. We disable app
3. We enable app, accepting all API scopes automatically (as with flag `--force-scopes`)

Pros:
* easy to manual update application

Cons:
* app can imitate that it's version changed, and rerequest some API scopes that was not granted to it.

**Comment by bigcat88** [comment]
Second solution:

1. Got another version then expected
2. We disable app immidiatly and notify admin about disabling(how can we know who shuold be notified?)

Pros:
* admin in this case, just should enable app in the UI or console and that's all

Cons:
* We do not know know whom can be notified about this. It is ugly to create such field only for the AppEcosystem. If we imagine such field will present in the Nextcloud ❤️


@julien-nc

**Comment by julien-nc** [comment]
> how can we know who shuold be notified?

All members of the admin group should be fine.

It feels weird to automatically accept new scopes from an ExApp. It makes the scope system useless when an ExApp is updated manually outside of NC.
I would go for the second solution.

Also, we could recommend not to manually update ExApps as it can lead to longer app downtimes (until an admin validates the new scopes).

Also, it is very likely that the person who updates an ExApp manually is a NC admin and knows it's wise to check the "app settings v2" to validate new scopes. So even if the notification is not perfect and can be seen late, it's good enough for a use case that is not recommended. We can decide people updating ExApps manually should know what they are doing and it's fine if the workflow is not perfect.

**Review by bigcat88 — CHANGES_REQUESTED** [review]
Till this got rewritten to new algo

**Comment by bigcat88** [comment]
will fix tomorrow, need to extend nc_py_api by adding two new APIs for extra applications.

**Pull request merged**
